https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline-2532742022/refs/heads/main/data/raw/G_actividad%20(1).csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline-2532742022/refs/heads/main/data/raw/G_actividad%20(1).csv"

df = pd.read_csv(url)

df.head()

  id_actividad id_usuario             accion      fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1      ACT9001      US512      cambio clave   2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta  2024-08-08 05:00:00  inventario

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_actividad     246 non-null    object
 1   id_usuario       238 non-null    object
 2   accion           246 non-null    object
 3   fecha_actividad  240 non-null    object
 4   modulo           246 non-null    object
dtypes: object(5)
memory usage: 9.7+ KB

id_actividad       0
id_usuario         8
accion             0
fecha_actividad    6
modulo             0
dtype: int64

In [9]:
#limpieza de datos
actividad = df.copy()

actividad.columns = actividad.columns.str.strip().str.lower()

for col in actividad.select_dtypes(include='object').columns: actividad[col] = actividad[col].astype(str).str.strip()

actividad = actividad.replace(r'^\s*$', pd.NA, regex=True)

actividad['id_usuario'] = actividad['id_usuario'].str.upper()

actividad['fecha_actividad'] = pd.to_datetime(actividad['fecha_actividad'], errors='coerce',
    dayfirst=True)
actividad['fecha_actividad'] = actividad['fecha_actividad'].dt.strftime('%Y-%m-%d %H:%M:%S')


actividad = actividad.drop_duplicates()

/tmp/ipykernel_1312/3375149827.py:12: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  actividad['fecha_actividad'] = pd.to_datetime(actividad['fecha_actividad'], errors='coerce',

In [12]:
#SEPARAR DATOS VALIDOS Y RECHAZADOS
validos = actividad[
    actividad['id_usuario'].notna() &
    actividad['fecha_actividad'].notna()
].copy()

rechazados = actividad[
    actividad['id_usuario'].isna() &
    actividad['fecha_actividad'].isna()
].copy()

In [13]:
#CREA FILA MOTIVO DE RECHAZO
def motivo(row):

    motivos = []

    if pd.isna(row['id_usuario']):
        motivos.append("idusuario_vacio")

    if pd.isna(row['fecha_actividad']):
        motivos.append("fechaActividad_vacia")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [14]:
#EXPORTACIÓN DE ARCHIVOS --> ENVIAR A RECHAZADOS O VALIDOS
validos.to_csv("actividad_curated.csv", index=False)

rechazados.to_csv("actividad_rejects.csv", index=False)

In [15]:
#
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_agnz_user:0NeQE82pEYWiuecWGeGciNE7aO4ev1F1@dpg-d6qu6o9j16oc73eu7250-a.oregon-postgres.render.com/etl_seguros_agnz"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 41.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [16]:
#CARGAR DATOS EN POSTGRESQL
validos.to_sql(
    'actividad_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'actividad_rejects',
    engine,
    if_exists='append',
    index=False
)

0

In [19]:
#VALIDAR LA CARGA

pd.read_sql(
"SELECT * FROM actividad_curated LIMIT 10",
engine
)

  id_actividad id_usuario             accion      fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1      ACT9001      US512       cambio clave  2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta  2024-08-08 05:00:00  inventario
5      ACT9005      US477           consulta  2024-09-17 19:00:00   seguridad
6      ACT9006      US479       cambio clave  2024-07-07 11:00:00      ventas
7      ACT9007      US448       cambio clave  2024-09-09 06:00:00    reportes
8      ACT9008      US408             logout  2024-04-27 21:00:00   seguridad
9      ACT9009      US440  actualizar pedido  2024-07-27 11:00:00  inventario