https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline-2532742022/refs/heads/main/data/raw/G_login%20(1).csv

In [1]:
import pandas as pd

In [2]:
url = "https://raw.githubusercontent.com/GeorginaLissethJimenezVentura/etl-data-pipeline-2532742022/refs/heads/main/data/raw/G_login%20(1).csv"

df = pd.read_csv(url)

df.head()

  id_login id_usuario          fecha_login              ip
0   LG6000      US414  2024/08/22 05:00:00  192.168.18.198
1   LG6001      US418  2024-02-03 10:00:00   192.168.1.214
2   LG6002      US476  2024-01-11 21:00:00   192.168.20.28
3   LG6003      US449  2024-06-13 18:00:00  192.168.12.135
4   LG6004      US422  2024-08-26 00:00:00   192.168.11.22

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_login     236 non-null    object
 1   id_usuario   228 non-null    object
 2   fecha_login  229 non-null    object
 3   ip           233 non-null    object
dtypes: object(4)
memory usage: 7.5+ KB

id_login       0
id_usuario     8
fecha_login    7
ip             3
dtype: int64

In [6]:
# limpieza de datos
login = df.copy()

login.columns = login.columns.str.strip().str.lower()

for col in login.select_dtypes(include='object').columns: login[col] = login[col].astype(str).str.strip()

login = login.replace(r'^\s*$', pd.NA, regex=True)

login['id_usuario'] = login['id_usuario'].str.upper()

login['fecha_login'] = login['fecha_login'].str.replace('/', '-', regex=False)

login['fecha_login'] = pd.to_datetime(login['fecha_login'], errors='coerce',
    dayfirst=True)

login = login.drop_duplicates()

/tmp/ipykernel_2087/3418935393.py:14: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  login['fecha_login'] = pd.to_datetime(login['fecha_login'], errors='coerce',

In [8]:
#SEPARAR DATOS VALIDOS Y RECHAZADOS
validos = login[
    login['id_usuario'].notna() &
    login['fecha_login'].notna() &
    login['ip'].notna()
].copy()

rechazados = login[
    login['id_usuario'].notna() &
    login['fecha_login'].notna() &
    login['ip'].notna()
].copy()

In [9]:
#CREA FILA MOTIVO DE RECHAZO
def motivo(row):

    motivos = []

    if pd.isna(row['id_usuario']):
        motivos.append("id_vacio")

    if pd.isna(row['fecha_login']):
        motivos.append("fechaLogin_vacio")

    if pd.isna(row['ip']):
     motivos.append("ip_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [10]:
#EXPORTACIÓN DE ARCHIVOS --> ENVIAR A RECHAZADOS O VALIDOS
validos.to_csv("login_curated.csv", index=False)

rechazados.to_csv("login_rejects.csv", index=False)

In [11]:
#
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_seguros_agnz_user:0NeQE82pEYWiuecWGeGciNE7aO4ev1F1@dpg-d6qu6o9j16oc73eu7250-a.oregon-postgres.render.com/etl_seguros_agnz"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 52.4 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [12]:
#CARGAR DATOS EN POSTGRESQL
validos.to_sql(
    'login_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'login_rejects',
    engine,
    if_exists='append',
    index=False
)

218

In [13]:
#VALIDAR LA CARGA

pd.read_sql(
"SELECT * FROM login_curated LIMIT 10",
engine
)

  id_login id_usuario         fecha_login              ip
0   LG6000      US414 2024-08-22 05:00:00  192.168.18.198
1   LG6001      US418 2024-02-03 10:00:00   192.168.1.214
2   LG6002      US476 2024-01-11 21:00:00   192.168.20.28
3   LG6003      US449 2024-06-13 18:00:00  192.168.12.135
4   LG6004      US422 2024-08-26 00:00:00   192.168.11.22
5   LG6005      US507 2024-05-06 15:00:00   192.168.18.36
6   LG6006      US487 2024-09-22 13:00:00   192.168.16.20
7   LG6007      US423 2024-07-16 17:00:00    192.168.4.86
8   LG6008      US426 2024-05-11 09:00:00   192.168.11.13
9   LG6009      US422 2024-02-07 05:00:00    192.168.9.56